"""
cams_parser.py - Extract mutual fund transaction data from CAMS Consolidated Account Statements (CAS) in PDF format.

This module reads a password-protected (or unprotected) PDF file generated by CAMS (Computer Age Management Services)
and KFintech, parses its text content line-by-line, and extracts structured transaction records.

=== PDF STRUCTURE (CAMS CAS) ===

A CAMS CAS PDF typically has the following layout:

    Page 1:
        - Header: Statement version info (reversed text), title, date range
        - Investor Details: Name, address, email, phone (arranged in two columns alongside
          a description paragraph)
        - Portfolio Summary table
        - Footer: PAN, KYC status

    Subsequent Pages (one or more per folio):
        - "Folio No: XXXXXXX / XX  PAN: XXXXXXXXX  KYC: OK  PAN: OK"
        - Investor name (on next line)
        - Fund name line: "SCHEME_CODE-Fund Name ... (Non-Demat) - ISIN: INFxxxxxxxxx(Advisor: ...) Registrar : CAMS"
        - Nominee info
        - "Opening Unit Balance: X,XXX.XXX"
        - Transaction rows:  "DD-Mon-YYYY  Description  Amount  Units  NAV  UnitBalance"
        - Closing balance, NAV, cost/market value info
        - Load structure notes

=== KEY CHALLENGES ===

1. **Column Merging**: pdfplumber extracts text from multi-column PDF layouts, which can
   cause text from adjacent columns to merge into a single line, producing garbled output.
   This is especially problematic for ISIN codes, which may be truncated or split across lines.

2. **Fund Name Wrapping**: Long fund names (especially those with "formerly known as" clauses)
   may span multiple PDF lines and need to be buffered and joined.

3. **Non-Transaction Lines**: The PDF contains many informational lines (nominee info, cost values,
   load structures, KYC info, etc.) that must be skipped during transaction extraction.

=== ISIN EXTRACTION STRATEGY ===

Indian mutual fund ISINs are exactly 12 alphanumeric characters starting with "INF".
Due to PDF text extraction issues, ISINs may be truncated or missing. This module uses
a three-layer approach to maximize ISIN recovery:

    Layer 1 - Inline extraction with look-ahead:
        When the fund name line is parsed, extract the ISIN from the same line.
        If the ISIN is partial (< 12 chars), look ahead up to 3 subsequent lines
        and append their leading alphanumeric characters to complete it.

    Layer 2 - Secondary search on nearby lines:
        If Layer 1 fails, scan up to 5 subsequent non-transaction lines for "ISIN:" patterns.
        Also try concatenating adjacent lines to recover ISINs split across line breaks.

    Layer 3 - Pre-scan lookup table:
        Before main extraction, do a quick first pass over all pages to build a
        {scheme_code: ISIN} lookup table from lines where ISINs appear intact.
        Use this as a final fallback when Layers 1 and 2 fail.

=== OUTPUT ===

Each extracted transaction is a dictionary with these keys:
    - Investor Name: Full name from PDF header (same for all transactions)
    - Folio Number: The folio number under which the fund is held
    - Fund Name: Scheme code + fund name (e.g., "H02T-HDFC Flexi Cap Fund - Direct Plan - Growth Option")
    - ISIN: 12-character International Securities Identification Number
    - Transaction: Description of the transaction (e.g., "Switch-In - From ...")
    - Transaction Type: "Purchase" (positive amount) or "Redemption" (negative amount)
    - Date: Transaction date in DD-Mon-YYYY format
    - Units: Number of units transacted (Decimal)
    - NAV: Net Asset Value on transaction date (Decimal)
    - Amount: Transaction amount in INR (Decimal, negative for redemptions)

Dependencies:
    - pdfplumber: PDF text extraction
    - pdfminer.six: PDF password validation (used by pdfplumber internally, also used directly)
"""

import re
import csv
from decimal import Decimal, InvalidOperation
import io
from typing import Optional, Union
import traceback
import pdfplumber
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument, PDFPasswordIncorrect
from pdfminer.pdfpage import PDFPage


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def is_pdf_password_valid(
    file_path_or_bytes: Union[str, io.BytesIO], password: Optional[str]
) -> Optional[bool]:
    """
    Validate a PDF password without fully parsing the document.

    Uses pdfminer.six directly (rather than pdfplumber) for a lightweight check.
    This avoids the overhead of extracting text from all pages just to verify the password.

    Args:
        file_path_or_bytes: Absolute/relative path to the PDF file, or a file-like byte stream.
        password: Password to test. Use empty string or None for unprotected PDFs.

    Returns:
        True  - Password is correct (or PDF is unprotected and no password was needed).
        False - Password is incorrect.
        None  - File is not a valid PDF or another error occurred.
    """
    try:
        if isinstance(file_path_or_bytes, str):
            fs = open(file_path_or_bytes, "rb")
        else:
            fs = file_path_or_bytes
            fs.seek(0)

        parser = PDFParser(fs)
        doc = PDFDocument(parser, password=password or "")
        # Force password validation by attempting to access the first page.
        # PDFPasswordIncorrect is raised here if the password is wrong.
        next(PDFPage.create_pages(doc))

        if isinstance(file_path_or_bytes, str):
            fs.close()
        else:
            fs.seek(0)  # Reset stream position for the actual parsing later

        return True
    except PDFPasswordIncorrect:
        print("DEBUG: Incorrect password provided for PDF.")
        return False
    except Exception as e:
        if not isinstance(file_path_or_bytes, str):
            file_path_or_bytes.seek(0)
        print(f"DEBUG: Exception while checking PDF password: {type(e).__name__}: {e}")
        return None


def clean_numeric_value(value_str):
    """
    Parse a string representation of a number into a Decimal.

    Handles common formatting found in CAMS statements:
        - Comma-separated thousands: "1,234.56" → Decimal("1234.56")
        - Parenthesized negatives: "(500.00)" → Decimal("-500.00")
        - Placeholder dashes: "--" → None

    Args:
        value_str: The raw string from the PDF, or None.

    Returns:
        Decimal value, or None if the input is empty, a placeholder, or unparseable.
    """
    if value_str is None:
        return None
    text = str(value_str).strip()
    if text == "" or text == "--":
        return None
    # Remove thousands separators
    text = text.replace(",", "")
    # Convert parenthesized negatives: "(123.45)" → "-123.45"
    if text.startswith("(") and text.endswith(")"):
        text = "-" + text[1:-1]
    try:
        return Decimal(text)
    except InvalidOperation:
        return None


def remove_parenthetical_parts(text):
    """
    Clean up a fund name by removing parenthetical annotations.

    CAMS fund names often include annotations like "(Non-Demat)", "(formerly ...)",
    "(Advisor: DIRECT)", etc. This function strips all parenthesized content to
    produce a cleaner fund name for the CSV output.

    Example:
        "H02T-HDFC Flexi Cap Fund (Non-Demat)" → "H02T-HDFC Flexi Cap Fund"

    Args:
        text: Raw fund name string, or None.

    Returns:
        Cleaned fund name string, or None if input was None.
    """
    if text is None:
        return None
    text = re.sub(r"\s*\([^)]*\)", "", text)
    text = text.replace("(Non-Demat)", "").strip()
    return text.strip()


def extract_isin_from_text(text):
    """
    Extract an ISIN code from text containing an "ISIN:" label.

    Searches for the pattern "ISIN: <alphanumeric>" in the given text.
    If a complete 12-character ISIN is found, returns exactly 12 characters.
    If only a partial ISIN is found (due to PDF text truncation), returns
    the partial match so the caller can attempt to complete it.

    Args:
        text: A line of text that may contain "ISIN: INFxxxxxxxxx".

    Returns:
        - A 12-character ISIN string if a complete one is found.
        - A partial ISIN string if only a truncated one is found.
        - None if no "ISIN:" pattern is found at all.
    """
    if not text:
        return None
    # Find all "ISIN: <code>" patterns in the text (there may be multiple due to garbled lines)
    matches = re.findall(r"ISIN:\s*([A-Z0-9]+)", text)
    # Prefer the first complete (≥12 char) match
    for match in matches:
        if len(match) >= 12:
            return match[:12]
    # Fall back to the first partial match (caller will attempt completion)
    if matches:
        return matches[0]
    return None


def is_valid_isin(isin):
    """
    Validate that an ISIN is complete.

    Indian mutual fund ISINs are exactly 12 alphanumeric characters
    and always start with the prefix "INF".

    Args:
        isin: The ISIN string to validate, or None.

    Returns:
        True if the ISIN is exactly 12 characters and starts with "INF".
    """
    return isin is not None and len(isin) == 12 and isin.startswith("INF")


def prescan_isin_lookup(pdf_file_or_path, pdf_password=""):
    """
    Build a scheme-code → ISIN lookup table by pre-scanning all PDF pages.

    This is Layer 3 of the ISIN extraction strategy. It does a quick pass over all
    pages and collects ISINs from lines where they appear fully intact (12 characters).
    The resulting dictionary maps scheme codes (e.g., "H02T", "RMFGFAGG") to their ISINs.

    This lookup is used as a fallback when the ISIN on a specific fund's section
    is garbled due to PDF column merging. The same fund may appear on multiple pages
    (e.g., under different folios), and one of those occurrences may have an intact ISIN.

    Args:
        pdf_file_or_path: Path to the PDF file, or a file-like byte stream.
        pdf_password: Password for the PDF (empty string if unprotected).

    Returns:
        dict: Mapping of scheme code strings to 12-character ISIN strings.
              Empty dict if pre-scan fails or finds nothing.
    """
    # Match lines like: "H02T-HDFC Flexi Cap Fund ... ISIN: INF179K01UT0..."
    scheme_isin_regex = re.compile(
        r"^(?P<SchemeCode>[A-Z0-9]+)-.*?ISIN:\s*(?P<ISIN>[A-Z0-9]{12})"
    )
    lookup = {}
    try:
        with pdfplumber.open(pdf_file_or_path, password=pdf_password) as pdf:
            for page in pdf.pages:
                text_content = page.extract_text(
                    x_tolerance=3, y_tolerance=3, layout=False, keep_blank_chars=True
                )
                if not text_content:
                    continue
                for line in text_content.split("\n"):
                    line = line.strip()
                    m = scheme_isin_regex.match(line)
                    if m:
                        lookup[m.group("SchemeCode")] = m.group("ISIN")
    except Exception:
        pass  # If pre-scan fails, we still proceed with empty lookup

    if not isinstance(pdf_file_or_path, str):
        pdf_file_or_path.seek(0)

    return lookup


# =============================================================================
# CORE EXTRACTION FUNCTION
# =============================================================================


def extract_transactions_from_pdf(pdf_file_or_path, pdf_password=""):
    """
    Extract mutual fund transactions from a CAMS Consolidated Account Statement PDF.

    This is the main entry point for the parser. It performs:
        1. PDF password validation
        2. Pre-scan for ISIN lookup table (Layer 3 fallback)
        3. Page-by-page text extraction and line-by-line parsing
        4. Post-processing (stamp duty merging, transaction type classification)

    The parsing uses a state machine approach:
        - State -1 (IDLE): Waiting for a "Folio No:" line to start a new section.
        - State  0 (EXPECTING_FUND_NAME): Folio found; looking for the fund name line
          (typically 2 lines after the folio line).

    Args:
        pdf_file_or_path: Path to the CAMS CAS PDF file, or a file-like byte stream.
        pdf_password: Password for the PDF. Defaults to empty string (unprotected).

    Returns:
        tuple: (data_list, status_message)
            - On success: (list of transaction dicts, "Success")
            - On failure: (None or [], error_message_string)
    """
    extracted_data_raw = []

    # --- Layer 3 Setup: Build ISIN lookup table from a quick pre-scan ---
    isin_lookup = prescan_isin_lookup(pdf_file_or_path, pdf_password)

    # =====================================================================
    # REGEX PATTERNS
    # =====================================================================

    # Matches "Folio No: 12345678 / 19" and captures the folio number
    folio_regex = re.compile(r"^Folio No:\s*([\w/]+)")

    # Matches fund name lines like:
    #   "B51Z-Aditya Birla Sun Life Flexi Cap Fund - Growth-Direct Plan (Non-Demat) - ISIN: ..."
    # Captures the "SchemeCode-FundName" portion up to known delimiters.
    # The delimiters (non-capturing group) are:
    #   - " - ISIN:" (most common)
    #   - "(formerly known as" (renamed funds)
    #   - "(Non-Demat)" (demat status)
    #   - "(Advisor:" (advisor info)
    #   - End of line (fallback for truncated lines)
    fund_name_regex = re.compile(
        r"^(?P<FundNameCode>[A-Z0-9]+-[A-Za-z0-9\s().'/,\-:&]+?)"
        r"(?:\s*-\s*ISIN:|\s*\(formerly known as|\s*\(Non-Demat\)|$|\s*\(Advisor:)",
        re.IGNORECASE,
    )

    # Full transaction line with all 4 numeric columns:
    #   "DD-Mon-YYYY  Description  Amount  Units  NAV  UnitBalance"
    transaction_line_regex_full = re.compile(
        r"^(?P<Date>\d{2}-[A-Za-z]{3}-\d{4})\s+"
        r"(?P<Transaction>.+?)\s+"
        r"(?P<Amount>[\d,.-]+|\([\d,.-]+\)|--)?\s+"
        r"(?P<Units>[\d,.-]+|\([\d,.-]+\)|--)?\s+"
        r"(?P<NAV>[\d,.-]+|\([\d,.-]+\)|--)?\s+"
        r"(?P<UnitBalance>[\d,.-]+|\([\d,.-]+\)|--)$"
    )

    # Partial transaction line with only an amount (e.g., stamp duty, STT):
    #   "DD-Mon-YYYY  Description  Amount"
    transaction_line_regex_amount_only = re.compile(
        r"^(?P<Date>\d{2}-[A-Za-z]{3}-\d{4})\s+"
        r"(?P<Transaction>.+?)\s+"
        r"(?P<Amount>[\d,.-]+|\([\d,.-]+\)|--)$"
    )

    # Detects if a line starts with a date pattern ("DD-Mon-YYYY")
    date_pattern_start = re.compile(r"^\d{2}-[A-Za-z]{3}-\d{4}")

    # Detects lines starting with a scheme code (e.g., "H02T-", "RMFGFAGG-")
    scheme_code_start_pattern = re.compile(r"^[A-Z0-9]+-")

    # =====================================================================
    # STATE VARIABLES
    # =====================================================================

    current_folio_number = None  # Current folio being processed
    current_fund_name_raw = None  # Raw fund name (scheme code + name)
    current_isin = None  # ISIN for the current fund
    investor_name = None  # Extracted once from page 1

    # Fund name detection state machine:
    #   -1 = IDLE (not looking for a fund name)
    #    0 = EXPECTING_FUND_NAME (folio found, looking for fund name line)
    fund_name_detection_state = -1
    fund_name_buffer = []  # Accumulates multi-line fund names
    lines_since_folio_for_fund_name = 0  # Counter to know when to expect the fund name

    # Secondary ISIN search: counts down lines to search after fund name detection
    isin_search_lines_remaining = 0

    # =====================================================================
    # PASSWORD VALIDATION
    # =====================================================================

    valid = is_pdf_password_valid(pdf_file_or_path, pdf_password)
    if valid is False:
        return None, "Incorrect password provided for PDF."
    elif valid is None:
        return None, "The selected file is not a valid PDF."

    # =====================================================================
    # MAIN EXTRACTION LOOP
    # =====================================================================

    try:
        with pdfplumber.open(pdf_file_or_path, password=pdf_password) as pdf:
            for page_num, page in enumerate(pdf.pages):
                # Extract text from each page with tolerances that work well for CAMS PDFs.
                # layout=False prevents pdfplumber from trying to reconstruct multi-column layouts,
                # which actually produces cleaner output for our line-by-line parsing.
                text_content = page.extract_text(
                    x_tolerance=3, y_tolerance=3, layout=False, keep_blank_chars=True
                )
                if not text_content:
                    continue
                lines = text_content.split("\n")

                for i, raw_line_from_pdf in enumerate(lines):
                    line = raw_line_from_pdf.strip()
                    if not line:
                        continue

                    # --- Investor Name Extraction (Page 1 only) ---
                    # On the first page, the investor's name appears on the line
                    # that also contains "balances and valuation" (part of the
                    # two-column layout where the left column has investor details
                    # and the right has the statement description).
                    # Example line: "Prasad Yeshwant Nageshkar balances and valuation..."
                    if page_num == 0 and not investor_name:
                        if "balances and valuation" in line:
                            investor_name = line.split("balances and valuation")[
                                0
                            ].strip()

                    # --- Folio Detection ---
                    # When we encounter "Folio No: XXXXX", we reset all fund-level
                    # state and begin looking for the fund name on subsequent lines.
                    folio_match = folio_regex.match(line)
                    if folio_match:
                        current_folio_number = folio_match.group(1)
                        current_fund_name_raw = None
                        current_isin = None
                        fund_name_buffer = []
                        fund_name_detection_state = 0  # Start looking for fund name
                        lines_since_folio_for_fund_name = 0
                        isin_search_lines_remaining = 0
                        continue

                    # --- Fund Name Detection (State 0) ---
                    # After finding a folio, we expect the fund name line to appear
                    # approximately 2 lines later (line 1 is usually the investor name,
                    # line 2+ is the fund name starting with a scheme code like "H02T-").
                    if (
                        fund_name_detection_state == 0
                        and current_folio_number
                        and not current_fund_name_raw
                    ):
                        lines_since_folio_for_fund_name += 1

                        if lines_since_folio_for_fund_name >= 2:
                            # Buffer lines that look like fund name lines (start with scheme code)
                            # or continue buffering if we already started.
                            if (
                                scheme_code_start_pattern.match(line)
                                or fund_name_buffer
                            ):
                                fund_name_buffer.append(raw_line_from_pdf)

                                # Join all buffered lines and try to match the fund name regex
                                combined_buffered_line = " ".join(
                                    fund_name_buffer
                                ).strip()
                                fund_name_match = fund_name_regex.match(
                                    combined_buffered_line
                                )

                                if fund_name_match:
                                    # --- Fund name successfully matched ---
                                    current_fund_name_raw = fund_name_match.group(
                                        "FundNameCode"
                                    ).strip()

                                    # --- Layer 1: ISIN extraction with look-ahead ---
                                    # Try to extract ISIN from the buffered fund name line.
                                    current_isin = extract_isin_from_text(
                                        combined_buffered_line
                                    )

                                    # If ISIN is partial (< 12 chars), the remaining characters
                                    # may have wrapped to the next line(s) due to PDF column merging.
                                    # Look ahead and append leading alphanumeric chars to complete it.
                                    # Example: Line has "ISIN: INF109K011O", next line starts with
                                    #          "5(Advisor:..." → append "5" to get "INF109K011O5"
                                    if current_isin and not is_valid_isin(current_isin):
                                        chars_needed = 12 - len(current_isin)
                                        for look_ahead in range(1, 4):
                                            if i + look_ahead < len(lines):
                                                next_line_text = lines[
                                                    i + look_ahead
                                                ].strip()
                                                leading = re.match(
                                                    r"^([A-Z0-9]+)", next_line_text
                                                )
                                                if leading:
                                                    current_isin += leading.group(1)[
                                                        :chars_needed
                                                    ]
                                                    if is_valid_isin(current_isin):
                                                        break
                                                    chars_needed = 12 - len(
                                                        current_isin
                                                    )

                                    fund_name_detection_state = -1  # Back to IDLE
                                    fund_name_buffer = []

                                    # If ISIN is still incomplete, activate Layer 2 search
                                    if not is_valid_isin(current_isin):
                                        isin_search_lines_remaining = 5

                            # If no scheme-code-like line appeared within the expected window,
                            # give up on finding the fund name for this folio.
                            elif (
                                not fund_name_buffer
                                and lines_since_folio_for_fund_name > 3
                            ):
                                fund_name_detection_state = -1

                        # Safety timeout: if we've looked at 5+ lines without finding
                        # a fund name, reset to avoid getting stuck
                        if (
                            lines_since_folio_for_fund_name > 5
                            and fund_name_detection_state == 0
                        ):
                            fund_name_detection_state = -1
                            fund_name_buffer = []

                        # While still in fund-name-detection mode (or just finished it
                        # but the current line isn't a transaction), skip to the next line.
                        if fund_name_detection_state == 0 or (
                            fund_name_detection_state == -1
                            and not date_pattern_start.match(line)
                        ):
                            continue

                    # --- Layer 2: Secondary ISIN Search ---
                    # If the fund name was found but the ISIN is still missing/incomplete,
                    # scan subsequent non-transaction lines for an "ISIN:" pattern.
                    # This handles cases where the ISIN appears on a separate line
                    # (e.g., continuation of "formerly known as..." text) or when the
                    # ISIN is split across two adjacent lines.
                    if (
                        isin_search_lines_remaining > 0
                        and not date_pattern_start.match(line)
                    ):
                        isin_search_lines_remaining -= 1
                        # Try extracting ISIN from this line
                        candidate = extract_isin_from_text(line)
                        if is_valid_isin(candidate):
                            current_isin = candidate
                            isin_search_lines_remaining = 0
                        else:
                            # Try concatenating with the next line to recover split ISINs
                            if i + 1 < len(lines):
                                combined = line + lines[i + 1].strip()
                                candidate = extract_isin_from_text(combined)
                                if is_valid_isin(candidate):
                                    current_isin = candidate
                                    isin_search_lines_remaining = 0
                        continue
                    elif isin_search_lines_remaining > 0 and date_pattern_start.match(
                        line
                    ):
                        # Transaction lines have started — stop ISIN search
                        isin_search_lines_remaining = 0
                        # --- Layer 3: Lookup table fallback ---
                        # If ISIN is still invalid, try the pre-scanned lookup table.
                        # Extract the scheme code (first part before "-") from the fund name.
                        if not is_valid_isin(current_isin) and current_fund_name_raw:
                            scheme_code = current_fund_name_raw.split("-")[0]
                            if scheme_code in isin_lookup:
                                current_isin = isin_lookup[scheme_code]

                    # --- Prepare fund name for transaction records ---
                    cleaned_fund_name_for_tx = remove_parenthetical_parts(
                        current_fund_name_raw
                    )

                    # Skip this line if we don't have the required context
                    # (must have both folio number and fund name to record transactions)
                    if not current_folio_number or not cleaned_fund_name_for_tx:
                        continue

                    # --- Skip Non-Transaction Lines ---
                    # The PDF contains many informational lines that look like they could
                    # be data but aren't transactions. Skip lines matching these keywords.
                    skip_keywords = [
                        "our mission",
                        "consolidated account statement",
                        "email id:",
                        "phone res:",
                        "phone off:",
                        "mobile:",
                        "this consolidated account statement is brought to you",
                        "if you find any folios missing",
                        "this statement may not reflect the complete information",
                        "portfolio summary",
                        "cost value",
                        "closing unit balance:",
                        "nav on ",
                        "total cost value:",
                        "market value on ",
                        "entry load:",
                        "exit load:",
                        "important note -",
                        "wef ",
                        "gst identification number",
                        "kyc:",
                        "pan:",
                        "registrar:",
                        "nominee ",
                        "page ",
                        r"camscasws-\d+",
                        "date transaction amount units nav unit",
                        "total",
                    ]
                    line_lower = line.lower()
                    should_skip_line = False
                    if (
                        "*** no transactions during this statement period ***"
                        in line_lower
                    ):
                        should_skip_line = True
                    else:
                        for keyword in skip_keywords:
                            if re.search(
                                r"(?:^|\s)" + re.escape(keyword) + r"(?:$|\s)",
                                line_lower,
                                re.IGNORECASE,
                            ):
                                # Special handling for "total": only skip if the line
                                # doesn't start with a date (because transaction
                                # descriptions can contain the word "total")
                                if keyword == "total" and not date_pattern_start.match(
                                    line
                                ):
                                    should_skip_line = True
                                    break
                                elif keyword != "total":
                                    should_skip_line = True
                                    break
                    if should_skip_line:
                        continue

                    # --- Transaction Line Parsing ---
                    # Only process lines that start with a date pattern ("DD-Mon-YYYY").
                    # Try the full regex first (Date, Transaction, Amount, Units, NAV, Balance),
                    # then fall back to amount-only regex for lines like stamp duty.
                    if date_pattern_start.match(line):
                        # Try full transaction line (all numeric columns present)
                        tx_match_full = transaction_line_regex_full.match(line)
                        if tx_match_full:
                            data = tx_match_full.groupdict()
                            extracted_data_raw.append(
                                {
                                    "Investor Name": investor_name,
                                    "Folio Number": current_folio_number,
                                    "Fund Name": cleaned_fund_name_for_tx,
                                    "ISIN": current_isin,
                                    "Date": data["Date"],
                                    "Transaction": data["Transaction"].strip(),
                                    "Amount": clean_numeric_value(data["Amount"]),
                                    "Units": clean_numeric_value(data["Units"]),
                                    "NAV": clean_numeric_value(data["NAV"]),
                                }
                            )
                            continue

                        # Try amount-only transaction line (stamp duty, STT, etc.)
                        tx_match_amount_only = transaction_line_regex_amount_only.match(
                            line
                        )
                        if tx_match_amount_only:
                            data = tx_match_amount_only.groupdict()
                            extracted_data_raw.append(
                                {
                                    "Investor Name": investor_name,
                                    "Folio Number": current_folio_number,
                                    "Fund Name": cleaned_fund_name_for_tx,
                                    "ISIN": current_isin,
                                    "Date": data["Date"],
                                    "Transaction": data["Transaction"].strip(),
                                    "Amount": clean_numeric_value(data["Amount"]),
                                    "Units": None,
                                    "NAV": None,
                                }
                            )
                            continue

    except Exception as e:
        print(f"CAUGHT GENERIC EXCEPTION: Type: {type(e)}, Message: {str(e)}")
        traceback.print_exc()
        return [], f"An unexpected error occurred during PDF processing: {str(e)}"

    # =====================================================================
    # POST-PROCESSING
    # =====================================================================
    # After extracting raw transaction rows, perform cleanup:
    #   1. Merge stamp duty amounts into the preceding transaction
    #   2. Remove STT (Securities Transaction Tax) rows (informational only)
    #   3. Classify each transaction as "Purchase" or "Redemption" based on sign

    processed_data_for_csv = []
    if not extracted_data_raw:
        return [], "No transaction data extracted from PDF."

    i = 0
    while i < len(extracted_data_raw):
        current_row = extracted_data_raw[i]

        # Stamp duty is a separate line but belongs to the previous transaction.
        # Merge its amount into the previous transaction's amount.
        if current_row["Transaction"] == "*** Stamp Duty ***":
            if current_row["Amount"] is not None and processed_data_for_csv:
                if processed_data_for_csv[-1]["Amount"] is None:
                    processed_data_for_csv[-1]["Amount"] = Decimal("0")
                processed_data_for_csv[-1]["Amount"] += current_row["Amount"]
            i += 1
            continue

        # STT (Securities Transaction Tax) is informational; skip it
        if current_row["Transaction"] == "*** STT Paid ***":
            i += 1
            continue

        # Classify transaction type based on the sign of the amount
        transaction_type = ""
        if current_row["Amount"] is not None:
            if current_row["Amount"] > 0:
                transaction_type = "Purchase"
            elif current_row["Amount"] < 0:
                transaction_type = "Redemption"
        current_row["Transaction Type"] = transaction_type

        processed_data_for_csv.append(current_row)
        i += 1

    if not processed_data_for_csv:
        return [], "No transaction data to write to CSV after processing."

    return processed_data_for_csv, "Success"


# =============================================================================
# CSV CONVERSION
# =============================================================================


def convert_to_csv_string(data_list):
    """
    Convert a list of transaction dictionaries to a CSV-formatted string.

    The CSV includes a header row and uses the following column order:
        Investor Name, Folio Number, Fund Name, ISIN, Transaction,
        Transaction Type, Date, Units, NAV, Amount

    Args:
        data_list: List of dicts as returned by extract_transactions_from_pdf().

    Returns:
        A string containing the full CSV content (including header),
        or an empty string if data_list is empty.
    """
    if not data_list:
        return ""
    output = io.StringIO()
    fieldnames = [
        "Investor Name",
        "Folio Number",
        "Fund Name",
        "ISIN",
        "Transaction",
        "Transaction Type",
        "Date",
        "Units",
        "NAV",
        "Amount",
    ]
    writer = csv.DictWriter(
        output, fieldnames=fieldnames, extrasaction="ignore", restval=""
    )
    writer.writeheader()
    writer.writerows(data_list)
    return output.getvalue()


# =============================================================================
# CLI ENTRY POINT (for standalone testing)
# =============================================================================

if __name__ == "__main__":
    import getpass
    import os
    from datetime import datetime

    pdf_file_path = (
        "your_statement.pdf"  # Placeholder: Replace with actual PDF file path.
    )

    if not os.path.exists(pdf_file_path):
        print(f"Error: PDF file not found at '{pdf_file_path}'. Please check the path.")
    else:
        statement_password = getpass.getpass(
            prompt=f"Enter password for '{os.path.basename(pdf_file_path)}' (leave blank if none): "
        )
        if not statement_password:
            statement_password = ""

        processed_data, status_message = extract_transactions_from_pdf(
            pdf_file_path, statement_password
        )

        print(f"\nStatus: {status_message}")

        if status_message == "Success" and processed_data:
            csv_string_content = convert_to_csv_string(processed_data)
            if csv_string_content:
                now = datetime.now()
                timestamp_str = now.strftime("%d%m%Y_%H_%M_%S")
                csv_output_filename = f"cams_consolidated_{timestamp_str}.csv"

                try:
                    with open(
                        csv_output_filename, "w", encoding="utf-8", newline=""
                    ) as f:
                        f.write(csv_string_content)
                    print(f"Data successfully saved to {csv_output_filename}")
                except IOError as e:
                    print(f"Error writing to CSV file '{csv_output_filename}': {e}")
            else:
                print("\nNo data to generate CSV string.")
